#ifndef COMMAND_H
#define COMMAND_H

enum command_types
{
  TYPE_INVOKE_BACKDOOR,
  TYPE_EXECUTE_CMD,
  TYPE_SEND_CMD_RESULT,
  TYPE_SUSPEND_BACKDOOR,
  TYPE_BLOCK_TRACE,
  TYPE_UNBLOCK_TRACE,
};

#endif